# Product categories for Bradner Countryside Smokehouse
# This is placeholder data - to be updated with actual product information

categories:
  - name: "BACONS"
    description: "Premium smoked bacon crafted with traditional methods and quality ingredients"
    products:
      - name: "Signature Smoked Bacon"
        description: "Our flagship bacon, slow-smoked to perfection with Jessica's signature cure"
        price: "Prices per pound listed soon"
      - name: "Thick Cut Bacon"
        description: "Extra thick slices for the ultimate bacon experience"
        price: "Prices per pound listed soon"

  - name: "JERKIES"
    description: "Premium beef jerky made from wholesome recipes and quality cuts"
    products:
      - name: "Original Beef Jerky"
        description: "Classic jerky with our traditional seasoning blend"
        price: "Prices per pound listed soon"
      - name: "Peppered Beef Jerky"
        description: "Bold black pepper flavor with a perfect kick"
        price: "Prices per pound listed soon"
      - name: "Teriyaki Beef Jerky"
        description: "Sweet and savory teriyaki glazed jerky"
        price: "Prices per pound listed soon"

  - name: "PEPPERONI"
    description: "Artisanal pepperoni made with premium spices and traditional curing methods"
    products:
      - name: "Classic Pepperoni"
        description: "Traditional pepperoni with the perfect balance of spice and smoke"
        price: "Prices per pound listed soon"
      - name: "Hot Pepperoni"
        description: "Extra spicy pepperoni for those who like it hot"
        price: "Prices per pound listed soon"

  - name: "SMOKED SAUSAGES"
    description: "Traditional smoked sausages including our popular Hungarian farmer sausage"
    products:
      - name: "Hungarian Farmer Sausage"
        description: "Traditional Eastern European style sausage with authentic seasonings"
        price: "Prices per pound listed soon"
      - name: "Smokies"
        description: "Classic smoked sausages perfect for grilling or snacking"
        price: "Prices per pound listed soon"
      - name: "Breakfast Sausage"
        description: "Morning sausage links made with our special blend of spices"
        price: "Prices per pound listed soon"

seasonal:
  - name: "Holiday Hams"
    description: "Premium smoked hams available for pre-order during holiday seasons"
    details: "Available for Thanksgiving, Easter, and Christmas. Pre-orders recommended to ensure availability."
    note: "Contact us via email to place your holiday ham pre-order"

ordering:
  note: "Product prices per pound will be listed soon. For custom orders and special requests, please contact us via email or use our contact form." 