# Product categories for Bradner Countryside Smokehouse
# This is placeholder data - to be updated with actual product information

categories:
  - name: "Smoked Meats"
    description: "Premium smoked meats prepared with traditional methods"
    products:
      - name: "Smoked Beef Brisket"
        description: "Slow-smoked beef brisket with our signature rub"
        price: "Contact for pricing"
      - name: "Smoked Pork Shoulder"
        description: "Tender pulled pork, perfect for sandwiches"
        price: "Contact for pricing"
      - name: "Smoked Ribs"
        description: "Fall-off-the-bone tender ribs"
        price: "Contact for pricing"
  
  - name: "Sausages"
    description: "Artisanal sausages made from quality local ingredients"
    products:
      - name: "Traditional Bratwurst"
        description: "Classic German-style bratwurst"
        price: "Contact for pricing"
      - name: "Italian Sausage"
        description: "Spicy Italian sausage with herbs and spices"
        price: "Contact for pricing"
      - name: "Breakfast Sausage"
        description: "Perfect for morning meals"
        price: "Contact for pricing"
  
  - name: "Specialty Items"
    description: "Unique smoked products and seasonal offerings"
    products:
      - name: "Smoked Salmon"
        description: "Pacific Northwest salmon, cold-smoked to perfection"
        price: "Contact for pricing"
      - name: "Smoked Cheese"
        description: "Local cheese enhanced with subtle smoke flavors"
        price: "Contact for pricing"
      - name: "Jerky"
        description: "High-protein snack in various flavors"
        price: "Contact for pricing"

services:
  - name: "Custom Smoking"
    description: "We'll smoke your meat to your specifications"
    details: "Bring your own meat and we'll smoke it with our expertise"
  
  - name: "Wholesale Orders"
    description: "Bulk orders for restaurants and retailers"
    details: "Special pricing available for volume orders"
  
  - name: "Catering Services"
    description: "Perfect for events and special occasions"
    details: "Let us provide smoked meats for your next gathering" 